###Llegar a los htmls:
GET / HTTP/1.1
###
GET /s HTTP/1.1
###
GET /account HTTP/1.1
###
GET /login HTTP/1.1
###
GET /signin HTTP/1.1
###
GET /editPassword HTTP/1.1
###
GET /deleteAccount HTTP/1.1
###
GET /logout HTTP/1.1
###
GET /rooms HTTP/1.1
###
GET /createRoom HTTP/1.1
###
GET /joinRoom HTTP/1.1
###
GET /room HTTP/1.1
###
GET /roomEdit HTTP/1.1
###
GET /roomDel HTTP/1.1
###
GET /roomExit HTTP/1.1
###
GET /goRoom* HTTP/1.1
###
GET /roomAll HTTP/1.1
###
GET /about HTTP/1.1
###
GET /settings HTTP/1.1
###





###Recibir datos basicos de usuario sin contrasegna
GET /b/user/:id HTTP/1.1

###Recibir datos basicos de usuario para el miniperfil
GET /b/userProfile/:id

###Crear usuario
POST /b/user HTTP/1.1
Content-Type: application/json

{
    "nombre":"X",
    "contrasegna":"X",
    "urlFoto":"X",
    "descripcion":"X",
    "modoOscuro":"X",
    "salas":[""]
}

###Borrar usuario y todo lo que ello implica
POST /b/userDel/:id HTTP/1.1
Content-Type: application/json

{
    "contrasegna":"X"
}

###Editar usuario
PUT /b/user/:id HTTP/1.1
Content-Type: application/json

{
    "nombre":"X",
    "urlFoto":"X",
    "descripcion":"X",
    "modoOscuro":"X"
}

###Hacer login
POST /b/userLogin HTTP/1.1
Content-Type: application/json

{
    "nombre":"X",
    "contrasegna":"X"
}

###Recibir contrasegna
GET /b/userp/:id HTTP/1.1

###Editar contrasegna
PUT /b/userp/:id HTTP/1.1
Content-Type: application/json

{
    "nuevaContrasegna": "X",
    "viejaContrasegna": "X2"
}

###Cambiar si el usuario ha creado su sala privada
PUT /b/userpb/:id HTTP/1.1
Content-Type: application/json

{
    "deja":"X"
}

###Saber si el usuario ya hizo su sala publica
GET /b/userpb/:id HTTP/1.1

###Devuelve los miembros de la sala
GET /b/roomMembers/:sala HTTP/1.1

###Informacion de perfilado de sala
GET /b/roomData/:sala HTTP/1.1

###Devuelve las salas de un usuario
GET /b/rooms/:id HTTP/1.1

###Devuelve el fundador de una sala
GET /b/founder/:sala HTTP/1.1

###Crear sala
POST /b/room/:id HTTP/1.1
Content-Type: application/json

{
    "nombre":"X",
    "idFundador":"X",
    "urlFoto":"X",
    "publica":"X",
    "descripcion":"X",
    "verID":"X"
}

###Unirse a una sala
POST /b/join/:id HTTP/1.1
Content-Type: application/json

{
    "sala":"X"
}

###Devuelve todas las salas publicas de la base de datos (lento)
GET /roomsPublic/:limit HTTP/1.1

###Edidar sala
PUT /b/roomEdit/:room/:user HTTP/1.1
Content-Type: application/json

{
    "nombre":"X",
    "verID":"X",
    "urlFoto":"X",
    "descripcion":"X",
    "publica":"X"
}

###Salir de sala
PUT /b/exit HTTP/1.1
Content-Type: application/json

{
    "usuario":"X",
    "sala":"X"
}

###Borrar sala y todo lo que ello implica
POST /b/roomdel HTTP/1.1
Content-Type: application/json

{
    "sala":"X",
    "usuario":"X"
}

###Conseguir x mensajes de una sala en un orden correcto
GET /b/roomMsg/:sala/:limit HTTP/1.1

###Conseguir todos los mensajes de una sala en un orden correcto (lento)
GET /b/roomMsgAll/:sala HTTP/1.1

###Decir un mensaje en una sala
POST /b/say/:sala HTTP/1.1
Content-Type: application/json

{
    "nombre":"X",
    "mensaje":"X",
    "idUsuario":"X",
    "urlFoto":"X"
}

###Borrar un mensaje de una sala
POST /b/saydel/:sala/:numero HTTP/1.1
Content-Type: application/json

{
    
}

###Editar un mensaje de una sala
PUT /b/say/:sala/:numero HTTP/1.1
Content-Type: application/json

{
    "nuevoTexto":"X"
}

